# -*- coding: utf-8 -*-
"""SetImageByPointAndDate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c5jzDMTt5pM88ApA8WcxLG8W_w-YIS9Q
"""

import ee
import os
import sys
import requests
import numpy as np
import pandas as pd
import geemap as geemap
from datetime import datetime
from sklearn.metrics import r2_score as r2, mean_squared_error
from tqdm import tqdm

service_account = 'mrsp-476@mrsp-414109.iam.gserviceaccount.com'
file_path = os.path.abspath(r'D:\Mohammad\app_map\map\basic_files\mrsp-414109-d4ddd84517dc.json')
credentials = ee.ServiceAccountCredentials(service_account, file_path)
ee.Initialize(credentials)

'''
::::: Functionality Summary :::::

Google Earth Engine (GEE) Initialization:

Authenticates using a service account and sets up the GEE environment.

Soil Data Processing:

process_soil_data() cleans and formats raw CSV data.

create_feature_collection() turns this data into a GEE FeatureCollection.

Vegetation and Soil Indices Extraction:

IindexExtractor class defines several indices (e.g., NDVI, NDMI, OPTRAM).

add_indices() applies these indices to a given Sentinel-2 image.

Image Collection Matching:

collect_images() fetches low-cloud Sentinel-2 images for each observation point and date range.

Timestamp Matching:

find_best_time() pairs each image with the closest sensor timestamp.

Image Sampling:

sampled_collection() samples pixel values at sensor locations and attaches moisture data.

Chunked Data Splitting:

split_dataframe_by_days() chunks large datasets by day to avoid GEE memory/time limits.
'''

class IindexExtractor:
    def __init__(self, scale):
        self.scale = scale

    def optram(self, image):
        # Select bands and apply scaling factor
        bands = image.select('B.*').multiply(0.0001)

        # Compute NDVI and STR indices
        NDVI = bands.normalizedDifference(['B8', 'B4']).rename('ndvi')
        STR = bands.expression('((1 - swir) ** 2) / (2 * swir)', {'swir': bands.select('B12')}).rename('str')
        stack = ee.Image.cat([NDVI, STR])

        # Apply thresholds for full vegetation and bare soil
        thr_full = NDVI.gt(0.3)
        str_full = STR.updateMask(thr_full)

        thr_bare = NDVI.gte(0).And(NDVI.lt(0.2))
        str_bare = STR.updateMask(thr_bare)

        # Calculate VW, VD, IW, ID values over the region of interest
        vw = ee.Number(str_full.reduceRegion(
            reducer=ee.Reducer.max(),
            scale=self.scale
        ).get('str'))

        vd = ee.Number(str_full.reduceRegion(
            reducer=ee.Reducer.min(),
            scale=self.scale
        ).get('str'))

        iw = ee.Number(str_bare.reduceRegion(
            reducer=ee.Reducer.max(),
            scale=self.scale
        ).get('str'))

        id = ee.Number(str_bare.reduceRegion(
            reducer=ee.Reducer.min(),
            scale=self.scale
        ).get('str'))

        # Calculate SW and SD values
        sw = vw.subtract(iw)
        sd = vd.subtract(id)

        # Create the soil moisture index
        mask = NDVI.lt(-0.1).Not()
        index = stack.expression(
            '(id + sd * ndvi - str) / (id - iw + (sd - sw) * ndvi)',
            {
                'id': id,
                'sd': sd,
                'ndvi': NDVI,
                'str': STR,
                'iw': iw,
                'sw': sw
            }
        ).rename('OPTRM')

        # Return the final index with scaling and masking
        return index.updateMask(mask).copyProperties(image, image.propertyNames())

    def ndwi(self, image):

        NDWI = image.normalizedDifference(['B3', 'B8']).rename('NDWI')
        return NDWI

    def ndvi(self, image):

        NDVI = image.normalizedDifference(['B3', 'B8']).rename('NDVI')
        return NDVI

    def ndmi(self, image):

        NDMI = image.normalizedDifference(['B8', 'B11']).rename('NDMI');
        return NDMI

    def nsds(slef, image):
        NSDS = image.normalizedDifference(['B11', 'B12']).rename('NSDS');
        return NSDS

    def gvmi(self, image):
        # Implement GVMI formula
        GVMI = image.expression(
            '((nir + 0.1) - (swir + 0.02)) / ((nir + 0.1) + (swir + 0.02))',
            {
                'nir': image.select('B8'),
                'swir': image.select('B11')
            }
        ).rename('GVMI')
        return GVMI
    
def process_soil_data(file_path):
    """
    Load and process soil moisture data from a CSV file.

    Args:
        file_path (str): Path to the CSV file.

    Returns:
        pd.DataFrame: Processed DataFrame with additional columns.
        pd.DataFrame: DataFrame with unique day entries.
    """
    # Load the CSV
    df = pd.read_csv(file_path)

    df_clean = df.dropna()

    # Select relevant columns
    selected_columns = ['Latitude', 'Longitude', 'Reading Time', 'Moisture']
    df_clean = df_clean[selected_columns]

    # Convert 'Reading Time' to datetime format
    df_clean['Reading Time'] = pd.to_datetime(df_clean['Reading Time'], format='%Y-%m-%d %H:%M:%S')

    # Add Unix timestamp in milliseconds
    df_clean['time_ms'] = df_clean['Reading Time'].astype('int64') // 10**6

    # Extract date and time features
    df_clean['day'] = df_clean['Reading Time'].dt.date
    df_clean['hour'] = df_clean['Reading Time'].dt.strftime('%H:%M')

    # Get one record per day per location
    df_unique_day = df_clean.drop_duplicates(subset=['Latitude', 'Longitude', 'day'], keep='first')

    return df_clean, df_unique_day

def create_feature_collection(df):
    """
    Create a FeatureCollection from a DataFrame.

    Args:
        df (pd.DataFrame): Input DataFrame.

    Returns:
        ee.FeatureCollection: FeatureCollection created from the DataFrame.
    """ 
    pointFeatures = []
    # Iterate through the DataFrame's index
    for i, idx in enumerate(df.index): 
        row = df.loc[idx] # Use .loc to access row by index label
        point = ee.Geometry.Point([row['Longitude'], row['Latitude']])
        reading_day = ee.Date(str(row['day']))
        moisture = row['Moisture']

        feature = ee.Feature(point).set({
            'measure_moisture': moisture,
            'startDate': reading_day.advance(-1, 'day'),
            'endDate': reading_day.advance(1, 'day'),
            'id': i + 1,
            'latitude': point.coordinates().get(1),
            'longitude': point.coordinates().get(0)
        })

        pointFeatures.append(feature)

    return ee.FeatureCollection(pointFeatures)

def add_indices(image):
    # Instantiate IindexExtractor with the region of interest and scale
    index_extractor = IindexExtractor(10)

    # Compute indices using the instance of IindexExtractor
    optram_index = index_extractor.optram(image)
    ndwi_index = index_extractor.ndwi(image)
    ndvi_index = index_extractor.ndvi(image)
    ndmi_index = index_extractor.ndmi(image)
    nsds_index = index_extractor.nsds(image)
    gvmi_index = index_extractor.gvmi(image)

    # Add computed indices as new bands to the original image
    # return image.addBands([optram_index, ndwi_index, ndvi_index, ndmi_index, nsds_index, gvmi_index])
    return image.addBands([ndwi_index, ndvi_index, ndmi_index, nsds_index, gvmi_index])

def collect_images(feature):
    # Get the geometry (point) and date range from the feature
    point = feature.geometry()
    start = ee.Date(feature.get('startDate'))
    end = ee.Date(feature.get('endDate'))
    id = feature.get('id')

    # Filter Sentinel-2 collection by point and date range
    image_collection = ee.ImageCollection('COPERNICUS/S2_SR_HARMONIZED') \
        .filterBounds(point) \
        .filterDate(start, end) \
        .sort('CLOUDY_PIXEL_PERCENTAGE') \
        .select("B.*") \
        .map(add_indices)  # Assuming add_indices is defined elsewhere

    # Add startDate, endDate, and id properties to each image in the collection
    image_collection = image_collection.map(lambda image: image.set({
        'point_geometry':point,
        'startDate': start,
        'endDate': end,
        'id': id,
        'doy': ee.Date(image.get('system:time_start')).getRelative('day', 'year')
    }))

    # Select the least cloudy image (first in the sorted collection)
    # image = image_collection.first().toFloat()
    image = image_collection.first()

    # Check if an image exists, return the image as a collection or an empty collection
    return ee.Algorithms.If(image, ee.ImageCollection(image.toFloat()), ee.ImageCollection([]))

def find_best_time(imageCollection, df):
    """
    For each Earth Engine timestamp, find the closest row in the DataFrame based on 'time_ms'.

    Args:
        df (pd.DataFrame): DataFrame with a 'time_ms' column.
        images_info (list of dicts): List of dictionaries with 'id' and 'time_ms' for each image from Earth Engine.

    Returns:
        pd.DataFrame: Rows from df that are closest in time to each Earth Engine timestamp, along with the image ID.
    """

    # Get list of timestamps and IDs from Earth Engine
    image_times = imageCollection.aggregate_array('system:time_start').getInfo()
    image_ids = imageCollection.aggregate_array('id').getInfo()

    # Combine into list of dictionaries
    images_info = [{'id': img_id, 'time_ms': ts} for img_id, ts in zip(image_ids, image_times)]

    matched_rows = []

    for img_info in images_info:
        ts = img_info['time_ms']  # Extract the timestamp (time_ms)
        image_id = img_info['id']  # Extract the image ID

        # Compute the absolute difference and find the index of the closest row
        closest_idx = (df['time_ms'] - ts).abs().idxmin()

        # Get the closest row and copy it to avoid SettingWithCopyWarning
        closest_row = df.loc[closest_idx].copy()
        closest_row['image_id'] = image_id  # Add the image ID to the copied row

        # Append the corresponding row with the image ID
        matched_rows.append(closest_row)

    # Combine into a DataFrame and reset index
    return pd.DataFrame(matched_rows).reset_index(drop=True)

def create_best_feature_collection(df):
    """
    Convert a DataFrame of geolocated soil moisture readings into an Earth Engine FeatureCollection.

    Args:
        df (pd.DataFrame): DataFrame with columns ['Latitude', 'Longitude', 'Moisture', 'day'].
        limit (int): Number of rows to use from the DataFrame (default: 200).

    Returns:
        ee.FeatureCollection: A FeatureCollection of points with properties.
    """
    pointFeatures = []
    for i, row in df.iterrows():
        point = ee.Geometry.Point([row['Longitude'], row['Latitude']])
        reading_day = ee.Date(str(row['day']))
        moisture = row['Moisture']
        image_id = row['image_id']

        feature = ee.Feature(point).set({
            'measure_moisture': moisture,
            'startDate': reading_day,
            'endDate': reading_day.advance(1, 'day'),
            'id': image_id
        })

        pointFeatures.append(feature)

    return ee.FeatureCollection(pointFeatures)

def add_coordinates(feature):
    coords = feature.geometry().coordinates()
    return feature.set({
        'longitude': coords.get(0),
        'latitude': coords.get(1)
    })

def sampled_collection(imageCollection, pointCollection):
    image_ids = imageCollection.aggregate_array('id').getInfo()
    point_ids = pointCollection.aggregate_array('id').getInfo()

    common_ids = sorted(list(set(image_ids) & set(point_ids)))

    features = []

    for i, indx in tqdm(enumerate(common_ids), total=len(common_ids), desc="Sampling"):
        # Get the image and point with matching ID
        filtered_image = imageCollection.filter(ee.Filter.eq('id', indx)).first()
        filtered_point = pointCollection.filter(ee.Filter.eq('id', indx)).first()

        if filtered_image is None or filtered_point is None:
            print(f"No image or point found for ID: {indx}")
            continue

        geom = filtered_point.geometry()

        # Use reduceRegion to get band values (float precision)
        reduced = filtered_image.reduceRegion(
            reducer=ee.Reducer.first(),  # or mean, if more suitable
            geometry=geom,
            scale=10,
            maxPixels=1e9
        )

        # Add the values and metadata as a new feature
        feature = ee.Feature(geom).set(reduced).set({
            'doy': ee.Date(filtered_image.get('system:time_start')).getRelative('day', 'year'),
            'id': indx,
            'measure_moisture': filtered_point.get('measure_moisture')
        })

        features.append(feature)

    # Combine all into one FeatureCollection
    return ee.FeatureCollection(features)

def split_dataframe_by_days(df, day_chunk_size=40, output_prefix="output_chunk", output_dir=".", fallback_dir="fallback"):
    # Drop rows with missing values
    df_clean = df.dropna()

    # Select relevant columns
    selected_columns = ['Latitude', 'Longitude', 'Reading Time', 'Moisture']
    df_clean = df_clean[selected_columns]

    # Convert 'Reading Time' to datetime
    df_clean['Reading Time'] = pd.to_datetime(df_clean['Reading Time'], format='%Y-%m-%d %H:%M:%S', errors='coerce')
    df_clean = df_clean.dropna(subset=['Reading Time'])

    # Add timestamp and time info
    df_clean['time_ms'] = df_clean['Reading Time'].astype('int64') // 10**6
    df_clean['day'] = df_clean['Reading Time'].dt.date
    df_clean['hour'] = df_clean['Reading Time'].dt.strftime('%H:%M')

    # Get all unique days sorted
    unique_days = sorted(df_clean['day'].unique())

    if len(unique_days) <= day_chunk_size:
        # Save original file if not enough days
        fallback_dir = os.path.abspath(fallback_dir)
        if not os.path.exists(fallback_dir):
            os.makedirs(fallback_dir)

        fallback_path = os.path.join(fallback_dir, f"{output_prefix}_original.csv")
        df.to_csv(fallback_path, index=False)
        print(f"⚠️ Not enough unique days. Original file saved to: {fallback_path}")
        return 0

    # Ensure output directory exists
    output_dir = os.path.abspath(output_dir)
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    file_count = 0
    for i in range(0, len(unique_days), day_chunk_size):
        day_chunk = unique_days[i:i+day_chunk_size]
        chunk_df = df_clean[df_clean['day'].isin(day_chunk)]

        chunk_filename = os.path.join(output_dir, f"{output_prefix}_{file_count + 1}.csv")
        chunk_df.to_csv(chunk_filename, index=False)
        file_count += 1

    print(f"✅ Done! Created {file_count} CSV files based on 40-day chunks.")
    return file_count

# ----------------------------------------------------------------------

csv_dir = r'D:\Mohammad\FarmingForecasterProcessed'
output_dir = r"D:\Mohammad\sep_csv"
fallback_dir = r"D:\Mohammad\fallback_csv"
csv_files = [os.path.join(csv_dir, f) for f in os.listdir(csv_dir) if f.endswith('.csv')]

print(f"🔍 Found {len(csv_files)} CSV files.")

for i, csv_file in enumerate(csv_files):
    print(f"📂 Processing file {i+1}/{len(csv_files)}: {csv_file}")
    df = pd.read_csv(csv_file)

    base_name = os.path.splitext(os.path.basename(csv_file))[0]
    split_dataframe_by_days(
        df,
        day_chunk_size=40,
        output_prefix=base_name,
        output_dir=output_dir,
        fallback_dir=fallback_dir
    )

csv_dir = r'D:\Mohammad\Output'
csv_files = [os.path.join(csv_dir, f) for f in os.listdir(csv_dir) if f.endswith('.csv')]

for csv_file in csv_files:
    # Extract filename without extension
    filename = os.path.splitext(os.path.basename(csv_file))[0]

    # Build output path
    output_path = rf'D:\Mohammad\sampledata\{filename}_sampled_data.csv'

    # Check if file already exists
    if os.path.exists(output_path):
        print(f"File {output_path} already exists. Skipping processing.")
        continue

    # Proceed with processing only if the file doesn't exist
    df_clean, df_unique_day = process_soil_data(csv_file)

    feature_collection = create_feature_collection(df_unique_day)
    image_collections = feature_collection.map(collect_images)

    # Initialize an empty ImageCollection
    emptyCollection = ee.ImageCollection([])

    # Flatten the collection to get a single ImageCollection
    final_image_collection = emptyCollection.merge(image_collections.flatten())

    # Match closest rows from your df
    best_point = find_best_time(imageCollection=final_image_collection, df=df_clean)
    bestPointCollection = create_best_feature_collection(best_point)

    # Sample data
    all_sampled_data = sampled_collection(
        imageCollection=final_image_collection,
        pointCollection=bestPointCollection
    )

    length = all_sampled_data.size().getInfo()
    print(f"Total number of sampled features in {filename}:", length)

    if length > 60:
        print(f"Too many features ({length}) in {filename}, skipping save.")
        continue

    # Save to CSV
    geemap.ee_to_csv(ee_object=all_sampled_data, filename=output_path)
    print(f"Sampled data saved to {output_path}")
